export const summaryList = [
  {
    id: 11,
    name: 'MOFA AG-GRID',
    company: 'United Overseas Bank',
    caption: 'ReactJS, AG-GRID, JIRA, BitBucket',
    year: 2019,
  },
  {
    id: 11,
    name: 'Temasek Connection 19',
    company: 'Temasek Holding Private Limited',
    caption: 'ReactJS, Strapi, JIRA, BitBucket, S3',
    year: 2019,
    isHighlight: true,
  },
  {
    id: 10,
    name: 'OCBC GBA',
    company: 'Overseas Chineces Banking Corporation',
    caption: 'ReactJS, BitBucket',
    year: 2019,
  },
  {
    id: 9,
    name: 'PEII Deal Tracker',
    company: 'Government Investment Company',
    caption: 'ReactJS, Redux, AG-Grid, JIRA, GitHub, Jenkins',
    year: 2018,
    isHighlight: true,
  },
  {
    id: 8,
    name: 'Intranet Revamp',
    company: 'Bank of Singapore',
    caption: 'Sharepoint, VanilaJS, HTML, CSS3',
    year: 2016,
  },
  {
    id: 7,
    name: 'Scan and Checkout',
    company: 'United Overseas Bank',
    caption: 'React Native, BitBucket',
    year: 2016,
  },
  {
    id: 6,
    name: 'BAU Velocity',
    company: 'Standard Chartered',
    caption: 'Cordova, EmberJS, JIRA, SVN',
    year: 2016,
  },
  {
    id: 5,
    name: 'Digital Signage System',
    company: 'Serial Multivision Pte Ltd',
    caption: 'C#, Angular, GitHub',
    year: 2016,
  },
  {
    id: 4,
    name: 'BYOD System',
    company: 'Serial Multivision Pte Ltd',
    caption: 'C#, Angular, GitHub',
    year: 2016,
    isHighlight: true,
  },
  {
    id: 3,
    name: 'Annoucement System',
    company: 'St Joseph Institution Junior',
    caption: 'Google Apps Script, JQuery',
    year: '2012',
  },
  {
    id: 2,
    name: 'Orphans United P/L 1',
    company: 'Cadmus Technologies P/L',
    caption: 'HTML, CSS, JQUERY',
    year: '2012',
  },
  {
    id: 1,
    name: 'Kampung Glam Cafe',
    company: 'Cadmus Technologies P/L',
    caption: 'HTML, CSS, JQUERY',
    year: '2012',
  },
  {
    id: 0,
    name: 'Entry System',
    company: 'Cadmus Technologies P/L',
    caption: 'C#, Crystal Report',
    year: '2012',
  },
];

// const detailData = [
//   {
//     id: 11,
//     name: 'Temasek Connection 19',
//     company: 'Temasek Holding Private Limited',
//     caption: 'ReactJS, Strapi, JIRA, BitBucket, S3',
//     year: 2019,
//     isHighlight: true,
//   },
// ];
